package it.thefedex87.notes_utils

object NotesConsts {
    const val NOTES_STATE = "NOTES_STATE"

    const val IS_LOADING_SAVED_STATE_HANDLE_KEY = "IS_LOADING"
    const val QUERY_SAVED_STATE_HANDLE_KEY = "QUERY_KEY"

    const val EDITING_BLOCK_NOTE_SAVED_STATE_HANDLE_KEY = "EDITING_BLOCK_NOTE"

    const val NOTES_PREFERENCES_NAME = "NOTES_PREFERENCES"
    const val BLOCK_NOTES_VISUALIZATION_TYPE_PREFERENCE_KEY = "BLOCK_NOTES_VISUALIZATION_TYPE_PREFERENCE"
}