package it.thefedex87.notes_utils

object NotesConsts {
    const val NOTES_STATE = "NOTES_STATE"

    const val IS_LOADING_SAVED_STATE_HANDLE_KEY = "IS_LOADING"
    const val QUERY_SAVED_STATE_HANDLE_KEY = "QUERY_KEY"

    const val ADD_EDIT_BLOCK_NOTE_SAVED_STATE_HANDLE_KEY = "ADD_EDIT_BLOCK_NOTE_KEY"
    const val DELETE_BLOCK_NOTE_SAVED_STATE_HANDLE_KEY = "DELETE_BLOCK_NOTE_KEY"

    const val ADD_EDIT_NOTE_TITLE_SAVED_STATE_HANDLE_KEY = "ADD_EDIT_NOTE_TITLE_KEY"
    const val ADD_EDIT_NOTE_BODY_SAVED_STATE_HANDLE_KEY = "ADD_EDIT_NOTE_BODY_KEY"
    const val SELECTED_NOTES_SAVED_STATE_HANDLE_KEY = "SELECTED_NOTES_KEY"
    const val NOTE_ID = "noteId"
    const val BLOCK_NOTE_ID = "blockNoteId"

    const val NOTES_PREFERENCES_NAME = "NOTES_PREFERENCES"
    const val BLOCK_NOTES_VISUALIZATION_TYPE_PREFERENCE_KEY = "BLOCK_NOTES_VISUALIZATION_TYPE_PREFERENCE"
    const val NOTES_VISUALIZATION_TYPE_PREFERENCE_KEY = "NOTES_VISUALIZATION_TYPE_PREFERENCE"
    const val NOTES_ORDER_BY_TYPE_PREFERENCE_KEY = "NOTES_ORDER_BY_PREFERENCE"
}